### ISSUE TITLE
Curtain doesn't show if chart and map are both included

### ISSUE THREAD

**Issue by markedmondson** [amcharts/dataloader#8]
When you have the map and chart files both included in a document the "loading" curtain doesn't consistently show.

With map: http://jsfiddle.net/6g6tcbb1/3/
Without map: http://jsfiddle.net/6g6tcbb1/4/

**Comment by martynasma** [comment]
When you use both amcharts.js and ammap.js on the same page, instead of ammap.js you should use ammap_amcharts_extension.js.

ammap.js creates amChart's core classes which effectively overrides some of the Data Loader's presets/settings.

The curtain shows up fine if I make the above change:

http://jsfiddle.net/6g6tcbb1/7/
